before_script:
  - export GOPATH=/golang
  - export PATH=$PATH:$GOPATH/bin
  - mkdir -p /golang/src/redborder/rb-malware-agent/
  - mv * /golang/src/redborder/rb-malware-agent/
  - cd /golang/src/redborder/rb-malware-agent/

stages:
  - build
  - test

check-go-1.5:
  image: golang:1.5
  stage: build
  script:
    - make get
    - make get_dev
    - make fmt
    - make vet
    - make errcheck
  allow_failure: true

build-go-1.5:
  image: golang:1.5
  stage: build
  script:
    - make get
    - make

test-go-1.5:
  image: golang:1.5
  stage: test
  script:
    - make get
    - make get_dev
    - make test
    - make cover
